@BASE_URL=http://localhost:3500
@Token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiaWF0IjoxNzc0ODI1MDQ1LCJleHAiOjE3NzQ5MTE0NDV9.TCjSd1uWY6B7xHP7v-1oLOBluKweGUT4SUZtIOA6oec

###
GET {{BASE_URL}}
### Login
POST {{BASE_URL}}/login
Content-Type: application/json

{
    "identity": "test1@example.com",
    "password": "hashedpassword"
}

### Register
POST {{BASE_URL}}/register
Content-Type: application/json

{    
    "username":"test999",
    "email":"tes29958@yahoo.com",
    "password":"te225511",
    "passwordConfirm":"te225511"
}

### GET
GET {{BASE_URL}}/user/profile
Authorization: Bearer {{Token}}

### PATCH
PATCH {{BASE_URL}}/user/profile
Content-Type: application/json
Authorization: Bearer {{Token}}

{"email":"user_patch@yahoo.com"}


### DELETE
DELETE {{BASE_URL}}/user/profile
Content-Type: application/json
Authorization: Bearer {{Token}}

{"userId":1}

### GET journal
GET {{BASE_URL}}/journal
Content-Type: application/json
Authorization: Bearer {{Token}}


### POST journal
POST {{BASE_URL}}/journal
Content-Type: application/json
Authorization: Bearer {{Token}}

{     "userId":5,
      "assetId": 7,
      "entryModelId": 5,
      "setUpTier": "A",
      "entryPrice": 42129.75,
      "margin": 123,
      "SL": 41718.4525,
      "TP": 44186.2375,
      "advantage": "Delicate depraedor dedecor doloribus arx ipsa aufero suppono dolores arcus.",
      "disadvantage": "Desolo tactus ultra careo expedita trepide.",
      "notes": "Vomica acquiro fugiat debilito communis beatae deludo baiulus vomito vicissitudo. Delectatio virtus valeo celer viduo coepi abundans enim. Labore cito totus terreo comptus advoco tyrannus.",
      "feedback": "Provident caterva natus centum sub.",
      "riskPerTrade":12,
      "side":"long"
    }

### PATCH
PATCH {{BASE_URL}}/journal/17
Content-Type: application/json
Authorization: Bearer {{Token}}

    {
      "entryModelId": 2,
      "setUpTier": "A",
      "entryPrice": 42129.75,
      "SL": 5555.4525,
      "TP": 4555.2375,
      "advantage": "1Delicate1 1depraedor1 dedecor doloribus arx ipsa aufero suppono dolores arcus.",
      "margin":1992,
      "disadvantage": "Desolo tactus ultra careo expedita trepide.",
      "notes": "Vomica acquiro fugiat debilito communis beatae deludo baiulus vomito vicissitudo. Delectatio virtus valeo celer viduo coepi abundans enim. Labore cito totus terreo comptus advoco tyrannus.",
      "feedback": "Provident caterva natus centum sub."
    }

### DELETE
DELETE {{BASE_URL}}/journal/16
Content-Type: application/json
Authorization: Bearer {{Token}}

### GET
GET {{BASE_URL}}/dashboard/pnl
Authorization: Bearer {{Token}}
### GET
GET {{BASE_URL}}/dashboard/winrate
Authorization: Bearer {{Token}}

### GET
GET {{BASE_URL}}/dashboard/riskreward
Authorization: Bearer {{Token}}

###
PATCH {{BASE_URL}}/journal/5
Content-Type: application/json
Authorization: Bearer {{Token}}

{"winLose":"WIN"}

###
GET {{BASE_URL}}/usermodel
Content-Type: application/json
Authorization: Bearer {{Token}}

### POST
POST {{BASE_URL}}/usermodel
Content-Type: application/json
Authorization: Bearer {{Token}}

{"name":"22222s",
"userId":5}

### DELETE
DELETE  {{BASE_URL}}/usermodel/16
Content-Type: application/json
Authorization: Bearer {{Token}}
