@BASE_URL=http://localhost:3500
@Token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNzc0OTQ5NDk2LCJleHAiOjE3NzUwMzU4OTZ9.mU5UfTXLt583xASoAk91uT0hE5_HVC1tj4g0NiK8Qys

### Login
POST {{BASE_URL}}/login
Content-Type: application/json

{
    "identity": "testuser",
    "password": "123456"
}

### Register
POST {{BASE_URL}}/register
Content-Type: application/json

{    
    "username":"test999",
    "email":"tes29958@yahoo.com",
    "password":"te225511",
    "passwordConfirm":"te225511"
}

### GET user/profile
GET {{BASE_URL}}/user/profile
Authorization: Bearer {{Token}}

### PATCH user/profile
PATCH {{BASE_URL}}/user/profile
Content-Type: application/json
Authorization: Bearer {{Token}}

{"email":"user_patch@yahoo.com"}


### DELETE user/profile
DELETE {{BASE_URL}}/user/profile
Content-Type: application/json
Authorization: Bearer {{Token}}

{"userId":2}

### GET journal
GET {{BASE_URL}}/journal
Content-Type: application/json
Authorization: Bearer {{Token}}


### POST journal
POST {{BASE_URL}}/journal
Content-Type: application/json
Authorization: Bearer {{Token}}

{     "userId":2,
      "assetId": 5,
      "entryModelId": 2,
      "setUpTier": "A",
      "entryPrice": 43729.75,
      "margin": 123,
      "SL": 43718.4525,
      "TP": 44186.2375,
      "advantage": "Delicate depraedor dedecor doloribus arx ipsa aufero suppono dolores arcus.",
      "disadvantage": "Desolo tactus ultra careo expedita trepide.",
      "notes": "Vomica acquiro fugiat debilito communis beatae deludo baiulus vomito vicissitudo. Delectatio virtus valeo celer viduo coepi abundans enim. Labore cito totus terreo comptus advoco tyrannus.",
      "feedback": "Provident caterva natus centum sub.",
      "riskPerTrade":12,
      "side":"LONG"
    }

### PATCH journal/:journalId
PATCH {{BASE_URL}}/journal/1
Content-Type: application/json
Authorization: Bearer {{Token}}

    {
      "entryModelId": 2,
      "setUpTier": "A",
      "entryPrice": 4567.78,
      "SL": 5555.4525,
      "TP": 4555.2375,
      "advantage": "1112221Delicate1 1depraedor1 dedecor doloribus arx ipsa aufero suppono dolores arcus.",
      "margin":1992,
      "disadvantage": "11121Desolo tactus ultra careo expedita trepide.",
      "notes": "Vomica acquiro fugiat debilito communis beatae deludo baiulus vomito vicissitudo. Delectatio virtus valeo celer viduo coepi abundans enim. Labore cito totus terreo comptus advoco tyrannus.",
      "feedback": "Provident caterva natus centum sub."
    }

### DELETE journal/:journalId
DELETE {{BASE_URL}}/journal/1
Content-Type: application/json
Authorization: Bearer {{Token}}

### GET /dashboard/pnl
GET {{BASE_URL}}/dashboard/pnl
Authorization: Bearer {{Token}}
### GET /dashboard/winrate
GET {{BASE_URL}}/dashboard/winrate
Authorization: Bearer {{Token}}

### GET /dashboard/riskreward
GET {{BASE_URL}}/dashboard/riskreward
Authorization: Bearer {{Token}}

### GET usermodel
GET {{BASE_URL}}/usermodel
Content-Type: application/json
Authorization: Bearer {{Token}}

### POST usermodel
POST {{BASE_URL}}/usermodel
Content-Type: application/json
Authorization: Bearer {{Token}}

{"modelName":"22222s",
"userId":4}

### DELETE usermodel/:usermodelId
DELETE  {{BASE_URL}}/usermodel/1
Content-Type: application/json
Authorization: Bearer {{Token}}


### GET Fund
GET {{BASE_URL}}/fundhistory/1
Authorization: Bearer {{Token}}

### GET asset
GET {{BASE_URL}}/asset